---
- name: Install latest passlib with pip (required for htpasswd command)
  pip:
    name: passlib
    state: latest
    extra_args: "{{ pip_extra_args }}"

- name: add users to htpasswd
  htpasswd: path=/etc/nginx/conf.d/registry.htpasswd name={{item.name}} password={{item.password}} owner=root group=root mode=0644
  with_items: docker_registry_users
  register: docker_registry_auth
