---

# Install prerequisites
  - name: make sure docker-python RPM is not installed for RedHat
    yum:
      name: docker-python
      state: absent
    when: ansible_os_family == "RedHat"

  - name: Install easy_install, python-dev package for Debian
    apt:
      pkg: "{{ item }}"
      state: latest
      update_cache: yes
      cache_valid_time: 3600
    sudo: yes
    with_items:
      - python-dev
      - python-setuptools #easy_install
    when: ansible_os_family == "Debian"

  - include: pip.yml

# Install and run docker registry
  - stat: path=/var/lib/docker-registry
    register: docker_registry_storage

  - name: Prepare Docker Registry Storage
    file:
      path: /var/lib/docker-registry
      state: directory
      mode: 750
    when: not docker_registry_storage.stat.exists #may already exist as a symbolic link

  - name: create config directory
    file: path="/etc/docker/registry" state="directory"

  - name: copy config
    template: src="config.yml.j2" dest="/etc/docker/registry/config.yml"

  - name: ensure Docker Registry is running
    docker:
      image: "registry:2"
#      memory_limit: 1024MB
      name: registry
      ports:
        - "127.0.0.1:5000:5000"
      env:
        REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
      volumes:
        - /var/lib/docker-registry:/registry:rw
        - /etc/docker/registry/config.yml:/etc/docker/registry/config.yml
      privileged: yes
      state: reloaded
      pull: missing
      restart_policy: always
    register: start_registry

#FIXME  - name: test Docker Registry
#    uri:
#      url: http://localhost:5000/v2/
#      status_code: 200
#      return_content: yes
#    register: test_docker_registry
#    until: test_docker_registry.content == '{}'
#    retries: 5
#    delay: 2

  - include: nginx.yml

