---
# Secure docker registry
- include: ssl.yml
  when: docker_registry_with_ssl|bool

- name: Install latest passlib with pip (required for htpasswd command)
  pip:
    name: passlib
    state: latest
    extra_args: "{{ pip_extra_args }}"

- name: add users to htpasswd
  htpasswd: path=/etc/nginx/conf.d/registry.htpasswd name={{item.name}} password={{item.password}} owner=root group=root mode=0644
  with_items: docker_registry_users
  register: docker_registry_auth

- template: src=docker-registry-v2.j2 dest=/etc/nginx/conf.d/docker-registry.conf owner=root group=root mode=0644
  register: docker_registry_vhost

- name: check if selinux is enabled
  command: getenforce
  register: selinux_status
  ignore_errors: yes
  changed_when: false

- name: to fix SELinux issue
  shell: setsebool -P httpd_can_network_connect 1
  when: selinux_status.rc != 0

- name: ensure Docker nginx is running
  docker:
    image: nginx:latest
    name: www-registry
    hostname: "{{ docker_registry_host }}"
    ports: "{{docker_registry_ip}}:{{docker_registry_port}}:443"
    links:
      - registry:registry
    volumes:
      - "/var/log/nginx/:/var/log/nginx:rw"
      - "/etc/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "/etc/nginx/certs:/etc/nginx/certs:ro"
    state: reloaded
    restart_policy: always
    privileged: yes
  register: start_nginx

- name: start firewalld
  service: name=firewalld state=started enabled=yes

- name: Open HTTPS for outer world
  firewalld: service=https permanent=true state=enabled zone=public immediate=true
